name=ArnoTek_Debug
version=1.0.2
author=Anthony Arnovitz, aarnovitz@arnotek.com
maintainer=Anthony Arnovitz, aarnovitz@arnotek.com
sentence=Conditional debugging utility for Arduino
paragraph=This utility conditionally generates Arduino C++ debugging statements.
category=Other
url=https://github.com/AJArnovitz/ArnoTek_Debug
architectures=avr